//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.0.0.
namespace VSTemplate
{
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Xml.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("LanguageTagValues", Namespace="http://schemas.microsoft.com/developer/vstemplate/2005")]
    public enum LanguageTagValues
    {
        
        Cpp,
        
        CSharp,
        
        Java,
        
        FSharp,
        
        Javascript,
        
        Python,
        
        R,
        
        Typescript,
        
        VisualBasic,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("PlatformTagValues", Namespace="http://schemas.microsoft.com/developer/vstemplate/2005")]
    public enum PlatformTagValues
    {
        
        Windows,
        
        Linux,
        
        [System.Xml.Serialization.XmlEnumAttribute("iOS")]
        IOS,
        
        [System.Xml.Serialization.XmlEnumAttribute("macOS")]
        MacOS,
        
        Android,
        
        Azure,
        
        [System.Xml.Serialization.XmlEnumAttribute("tvOS")]
        TvOS,
        
        Xbox,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ProjectTypeTagValues", Namespace="http://schemas.microsoft.com/developer/vstemplate/2005")]
    public enum ProjectTypeTagValues
    {
        
        Cloud,
        
        Console,
        
        DataScience,
        
        MachineLearning,
        
        Desktop,
        
        Extension,
        
        Games,
        
        IoT,
        
        Library,
        
        Mobile,
        
        Office,
        
        Other,
        
        Service,
        
        Test,
        
        UWP,
        
        Web,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("NameDescriptionIcon", Namespace="http://schemas.microsoft.com/developer/vstemplate/2005")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NameDescriptionIcon
    {
        
        /// <summary>
        /// <para xml:lang="de">Ruft den Text ab oder legt diesen fest.</para>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// </summary>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("Package", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Package { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("ID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ID { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("VSTemplate", Namespace="http://schemas.microsoft.com/developer/vstemplate/2005", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("VSTemplate", Namespace="http://schemas.microsoft.com/developer/vstemplate/2005")]
    public partial class VSTemplate
    {
        
        [System.Xml.Serialization.XmlElementAttribute("TemplateData", Namespace="http://schemas.microsoft.com/developer/vstemplate/2005")]
        public TemplateData TemplateData { get; set; }
        
        /// <summary>
        /// <para>_locID_text="TemplateContent" _locComment=""</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("_locID_text=\"TemplateContent\" _locComment=\"\"")]
        [System.Xml.Serialization.XmlElementAttribute("TemplateContent", Namespace="http://schemas.microsoft.com/developer/vstemplate/2005")]
        public VSTemplateTemplateContent TemplateContent { get; set; }
        
        /// <summary>
        /// <para>_locID_text="WizardExtension" _locComment=""</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("_locID_text=\"WizardExtension\" _locComment=\"\"")]
        [System.Xml.Serialization.XmlElementAttribute("WizardExtension", Namespace="http://schemas.microsoft.com/developer/vstemplate/2005")]
        public VSTemplateWizardExtension WizardExtension { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("WizardData", Namespace="http://schemas.microsoft.com/developer/vstemplate/2005")]
        public VSTemplateWizardData WizardData { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<System.Xml.XmlElement> _any;
        
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Collections.ObjectModel.Collection<System.Xml.XmlElement> Any
        {
            get
            {
                return this._any;
            }
            private set
            {
                this._any = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die Any-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the Any collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AnySpecified
        {
            get
            {
                return (this.Any.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="VSTemplate" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="VSTemplate" /> class.</para>
        /// </summary>
        public VSTemplate()
        {
            this._any = new System.Collections.ObjectModel.Collection<System.Xml.XmlElement>();
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute("Type", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Type { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("Version", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Version { get; set; }
    }
    
    /// <summary>
    /// <para>_locID_text="TemplateData" _locComment=""</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("_locID_text=\"TemplateData\" _locComment=\"\"")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TemplateData", Namespace="http://schemas.microsoft.com/developer/vstemplate/2005", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("TemplateData", Namespace="http://schemas.microsoft.com/developer/vstemplate/2005")]
    public partial class TemplateData
    {
        
        /// <summary>
        /// <para>_locID_text="TemplateData.Name" _locComment=""</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("_locID_text=\"TemplateData.Name\" _locComment=\"\"")]
        [System.Xml.Serialization.XmlElementAttribute("Name", Namespace="http://schemas.microsoft.com/developer/vstemplate/2005")]
        public NameDescriptionIcon Name { get; set; }
        
        /// <summary>
        /// <para>_locID_text="Description" _locComment=""</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("_locID_text=\"Description\" _locComment=\"\"")]
        [System.Xml.Serialization.XmlElementAttribute("Description", Namespace="http://schemas.microsoft.com/developer/vstemplate/2005")]
        public NameDescriptionIcon Description { get; set; }
        
        /// <summary>
        /// <para>_locID_text="Icon" _locComment=""</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("_locID_text=\"Icon\" _locComment=\"\"")]
        [System.Xml.Serialization.XmlElementAttribute("Icon", Namespace="http://schemas.microsoft.com/developer/vstemplate/2005")]
        public NameDescriptionIcon Icon { get; set; }
        
        /// <summary>
        /// <para>_locID_text="PreviewImage" _locComment=""</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("_locID_text=\"PreviewImage\" _locComment=\"\"")]
        [System.Xml.Serialization.XmlElementAttribute("PreviewImage", Namespace="http://schemas.microsoft.com/developer/vstemplate/2005")]
        public string PreviewImage { get; set; }
        
        /// <summary>
        /// <para>_locID_text="ProjectType" _locComment=""</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("_locID_text=\"ProjectType\" _locComment=\"\"")]
        [System.Xml.Serialization.XmlElementAttribute("ProjectType", Namespace="http://schemas.microsoft.com/developer/vstemplate/2005")]
        public string ProjectType { get; set; }
        
        /// <summary>
        /// <para>_locID_text="ProjectSubType" _locComment=""</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("_locID_text=\"ProjectSubType\" _locComment=\"\"")]
        [System.Xml.Serialization.XmlElementAttribute("ProjectSubType", Namespace="http://schemas.microsoft.com/developer/vstemplate/2005")]
        public string ProjectSubType { get; set; }
        
        /// <summary>
        /// <para>_locID_text="TemplateID" _locComment=""</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("_locID_text=\"TemplateID\" _locComment=\"\"")]
        [System.Xml.Serialization.XmlElementAttribute("TemplateID", Namespace="http://schemas.microsoft.com/developer/vstemplate/2005")]
        public string TemplateID { get; set; }
        
        /// <summary>
        /// <para>_locID_text="TemplateGroupID" _locComment=""</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("_locID_text=\"TemplateGroupID\" _locComment=\"\"")]
        [System.Xml.Serialization.XmlElementAttribute("TemplateGroupID", Namespace="http://schemas.microsoft.com/developer/vstemplate/2005")]
        public string TemplateGroupID { get; set; }
        
        /// <summary>
        /// <para>_locID_text="AppliesTo" _locComment=""</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("_locID_text=\"AppliesTo\" _locComment=\"\"")]
        [System.Xml.Serialization.XmlElementAttribute("AppliesTo", Namespace="http://schemas.microsoft.com/developer/vstemplate/2005")]
        public string AppliesTo { get; set; }
        
        /// <summary>
        /// <para>_locID_text="SortOrder" _locComment=""</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("_locID_text=\"SortOrder\" _locComment=\"\"")]
        [System.Xml.Serialization.XmlElementAttribute("SortOrder", Namespace="http://schemas.microsoft.com/developer/vstemplate/2005")]
        public string SortOrder { get; set; }
        
        /// <summary>
        /// <para>_locID_text="CreateNewFolder" _locComment=""</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("_locID_text=\"CreateNewFolder\" _locComment=\"\"")]
        [System.Xml.Serialization.XmlElementAttribute("CreateNewFolder", Namespace="http://schemas.microsoft.com/developer/vstemplate/2005")]
        public bool CreateNewFolder { get; set; }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die CreateNewFolder-Eigenschaft spezifiziert ist, oder legt diesen fest.</para>
        /// <para xml:lang="en">Gets or sets a value indicating whether the CreateNewFolder property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CreateNewFolderSpecified { get; set; }
        
        /// <summary>
        /// <para>_locID_text="DefaultName" _locComment=""</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("_locID_text=\"DefaultName\" _locComment=\"\"")]
        [System.Xml.Serialization.XmlElementAttribute("DefaultName", Namespace="http://schemas.microsoft.com/developer/vstemplate/2005")]
        public string DefaultName { get; set; }
        
        /// <summary>
        /// <para>_locID_text="ProvideDefaultName" _locComment=""</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("_locID_text=\"ProvideDefaultName\" _locComment=\"\"")]
        [System.Xml.Serialization.XmlElementAttribute("ProvideDefaultName", Namespace="http://schemas.microsoft.com/developer/vstemplate/2005")]
        public bool ProvideDefaultName { get; set; }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die ProvideDefaultName-Eigenschaft spezifiziert ist, oder legt diesen fest.</para>
        /// <para xml:lang="en">Gets or sets a value indicating whether the ProvideDefaultName property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ProvideDefaultNameSpecified { get; set; }
        
        /// <summary>
        /// <para>_locID_text="PromptForSaveOnCreation" _locComment=""</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("_locID_text=\"PromptForSaveOnCreation\" _locComment=\"\"")]
        [System.Xml.Serialization.XmlElementAttribute("PromptForSaveOnCreation", Namespace="http://schemas.microsoft.com/developer/vstemplate/2005")]
        public bool PromptForSaveOnCreation { get; set; }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die PromptForSaveOnCreation-Eigenschaft spezifiziert ist, oder legt diesen fest.</para>
        /// <para xml:lang="en">Gets or sets a value indicating whether the PromptForSaveOnCreation property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PromptForSaveOnCreationSpecified { get; set; }
        
        /// <summary>
        /// <para>_locID_text="EnableLocationBrowseButton" _locComment=""</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("_locID_text=\"EnableLocationBrowseButton\" _locComment=\"\"")]
        [System.Xml.Serialization.XmlElementAttribute("EnableLocationBrowseButton", Namespace="http://schemas.microsoft.com/developer/vstemplate/2005")]
        public bool EnableLocationBrowseButton { get; set; }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die EnableLocationBrowseButton-Eigenschaft spezifiziert ist, oder legt diesen fest.</para>
        /// <para xml:lang="en">Gets or sets a value indicating whether the EnableLocationBrowseButton property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EnableLocationBrowseButtonSpecified { get; set; }
        
        /// <summary>
        /// <para>_locID_text="EnableEditOfLocationField" _locComment=""</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("_locID_text=\"EnableEditOfLocationField\" _locComment=\"\"")]
        [System.Xml.Serialization.XmlElementAttribute("EnableEditOfLocationField", Namespace="http://schemas.microsoft.com/developer/vstemplate/2005")]
        public bool EnableEditOfLocationField { get; set; }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die EnableEditOfLocationField-Eigenschaft spezifiziert ist, oder legt diesen fest.</para>
        /// <para xml:lang="en">Gets or sets a value indicating whether the EnableEditOfLocationField property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EnableEditOfLocationFieldSpecified { get; set; }
        
        /// <summary>
        /// <para>_locID_text="Hidden" _locComment=""</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("_locID_text=\"Hidden\" _locComment=\"\"")]
        [System.Xml.Serialization.XmlElementAttribute("Hidden", Namespace="http://schemas.microsoft.com/developer/vstemplate/2005")]
        public bool Hidden { get; set; }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die Hidden-Eigenschaft spezifiziert ist, oder legt diesen fest.</para>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Hidden property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HiddenSpecified { get; set; }
        
        /// <summary>
        /// <para>_locID_text="LocationFieldMRUPrefix" _locComment=""</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("_locID_text=\"LocationFieldMRUPrefix\" _locComment=\"\"")]
        [System.Xml.Serialization.XmlElementAttribute("LocationFieldMRUPrefix", Namespace="http://schemas.microsoft.com/developer/vstemplate/2005")]
        public string LocationFieldMRUPrefix { get; set; }
        
        /// <summary>
        /// <para>_locID_text="NumberOfParentCategoriesToRollUp" _locComment=""</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("_locID_text=\"NumberOfParentCategoriesToRollUp\" _locComment=\"\"")]
        [System.Xml.Serialization.XmlElementAttribute("NumberOfParentCategoriesToRollUp", Namespace="http://schemas.microsoft.com/developer/vstemplate/2005")]
        public string NumberOfParentCategoriesToRollUp { get; set; }
        
        /// <summary>
        /// <para>_locID_text="CreateInPlace" _locComment=""</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("_locID_text=\"CreateInPlace\" _locComment=\"\"")]
        [System.Xml.Serialization.XmlElementAttribute("CreateInPlace", Namespace="http://schemas.microsoft.com/developer/vstemplate/2005")]
        public object CreateInPlace { get; set; }
        
        /// <summary>
        /// <para>_locID_text="BuildOnLoad" _locComment=""</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("_locID_text=\"BuildOnLoad\" _locComment=\"\"")]
        [System.Xml.Serialization.XmlElementAttribute("BuildOnLoad", Namespace="http://schemas.microsoft.com/developer/vstemplate/2005")]
        public object BuildOnLoad { get; set; }
        
        /// <summary>
        /// <para>_locID_text="BuildProjectOnLoad" _locComment=""</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("_locID_text=\"BuildProjectOnLoad\" _locComment=\"\"")]
        [System.Xml.Serialization.XmlElementAttribute("BuildProjectOnLoad", Namespace="http://schemas.microsoft.com/developer/vstemplate/2005")]
        public object BuildProjectOnLoad { get; set; }
        
        /// <summary>
        /// <para>_locID_text="ShowByDefault" _locComment=""</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("_locID_text=\"ShowByDefault\" _locComment=\"\"")]
        [System.Xml.Serialization.XmlElementAttribute("ShowByDefault", Namespace="http://schemas.microsoft.com/developer/vstemplate/2005")]
        public object ShowByDefault { get; set; }
        
        /// <summary>
        /// <para>_locID_text="LocationField" _locComment=""</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("_locID_text=\"LocationField\" _locComment=\"\"")]
        [System.Xml.Serialization.XmlElementAttribute("LocationField", Namespace="http://schemas.microsoft.com/developer/vstemplate/2005")]
        public TemplateDataLocationField LocationField { get; set; }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die LocationField-Eigenschaft spezifiziert ist, oder legt diesen fest.</para>
        /// <para xml:lang="en">Gets or sets a value indicating whether the LocationField property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LocationFieldSpecified { get; set; }
        
        /// <summary>
        /// <para>_locID_text="SupportsMasterPage" _locComment=""</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("_locID_text=\"SupportsMasterPage\" _locComment=\"\"")]
        [System.Xml.Serialization.XmlElementAttribute("SupportsMasterPage", Namespace="http://schemas.microsoft.com/developer/vstemplate/2005")]
        public bool SupportsMasterPage { get; set; }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die SupportsMasterPage-Eigenschaft spezifiziert ist, oder legt diesen fest.</para>
        /// <para xml:lang="en">Gets or sets a value indicating whether the SupportsMasterPage property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SupportsMasterPageSpecified { get; set; }
        
        /// <summary>
        /// <para>_locID_text="SupportsCodeSeparation" _locComment=""</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("_locID_text=\"SupportsCodeSeparation\" _locComment=\"\"")]
        [System.Xml.Serialization.XmlElementAttribute("SupportsCodeSeparation", Namespace="http://schemas.microsoft.com/developer/vstemplate/2005")]
        public bool SupportsCodeSeparation { get; set; }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die SupportsCodeSeparation-Eigenschaft spezifiziert ist, oder legt diesen fest.</para>
        /// <para xml:lang="en">Gets or sets a value indicating whether the SupportsCodeSeparation property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SupportsCodeSeparationSpecified { get; set; }
        
        /// <summary>
        /// <para>_locID_text="SupportsLanguageDropDown" _locComment=""</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("_locID_text=\"SupportsLanguageDropDown\" _locComment=\"\"")]
        [System.Xml.Serialization.XmlElementAttribute("SupportsLanguageDropdown", Namespace="http://schemas.microsoft.com/developer/vstemplate/2005")]
        public bool SupportsLanguageDropdown { get; set; }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die SupportsLanguageDropdown-Eigenschaft spezifiziert ist, oder legt diesen fest.</para>
        /// <para xml:lang="en">Gets or sets a value indicating whether the SupportsLanguageDropdown property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SupportsLanguageDropdownSpecified { get; set; }
        
        /// <summary>
        /// <para>_locID_text="AppendDefaultFileExtension" _locComment=""</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("_locID_text=\"AppendDefaultFileExtension\" _locComment=\"\"")]
        [System.Xml.Serialization.XmlElementAttribute("AppendDefaultFileExtension", Namespace="http://schemas.microsoft.com/developer/vstemplate/2005")]
        public bool AppendDefaultFileExtension { get; set; }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die AppendDefaultFileExtension-Eigenschaft spezifiziert ist, oder legt diesen fest.</para>
        /// <para xml:lang="en">Gets or sets a value indicating whether the AppendDefaultFileExtension property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AppendDefaultFileExtensionSpecified { get; set; }
        
        /// <summary>
        /// <para>_locID_text="RequiredFrameworkVersion" _locComment=""</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("_locID_text=\"RequiredFrameworkVersion\" _locComment=\"\"")]
        [System.Xml.Serialization.XmlElementAttribute("RequiredFrameworkVersion", Namespace="http://schemas.microsoft.com/developer/vstemplate/2005")]
        public TemplateDataRequiredFrameworkVersion RequiredFrameworkVersion { get; set; }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die RequiredFrameworkVersion-Eigenschaft spezifiziert ist, oder legt diesen fest.</para>
        /// <para xml:lang="en">Gets or sets a value indicating whether the RequiredFrameworkVersion property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RequiredFrameworkVersionSpecified { get; set; }
        
        /// <summary>
        /// <para>_locID_text="FrameworkVersion" _locComment=""</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("_locID_text=\"FrameworkVersion\" _locComment=\"\"")]
        [System.Xml.Serialization.XmlElementAttribute("FrameworkVersion", Namespace="http://schemas.microsoft.com/developer/vstemplate/2005")]
        public string FrameworkVersion { get; set; }
        
        /// <summary>
        /// <para>_locID_text="MaxFrameworkVersion" _locComment=""</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("_locID_text=\"MaxFrameworkVersion\" _locComment=\"\"")]
        [System.Xml.Serialization.XmlElementAttribute("MaxFrameworkVersion", Namespace="http://schemas.microsoft.com/developer/vstemplate/2005")]
        public TemplateDataMaxFrameworkVersion MaxFrameworkVersion { get; set; }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die MaxFrameworkVersion-Eigenschaft spezifiziert ist, oder legt diesen fest.</para>
        /// <para xml:lang="en">Gets or sets a value indicating whether the MaxFrameworkVersion property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MaxFrameworkVersionSpecified { get; set; }
        
        /// <summary>
        /// <para>_locID_text="TargetPlatformName" _locComment=""</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("_locID_text=\"TargetPlatformName\" _locComment=\"\"")]
        [System.Xml.Serialization.XmlElementAttribute("TargetPlatformName", Namespace="http://schemas.microsoft.com/developer/vstemplate/2005")]
        public string TargetPlatformName { get; set; }
        
        /// <summary>
        /// <para>_locID_text="RequiredPlatformVersion" _locComment=""</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("_locID_text=\"RequiredPlatformVersion\" _locComment=\"\"")]
        [System.Xml.Serialization.XmlElementAttribute("RequiredPlatformVersion", Namespace="http://schemas.microsoft.com/developer/vstemplate/2005")]
        public string RequiredPlatformVersion { get; set; }
        
        /// <summary>
        /// <para>_locID_text="MaxOSVersion" _locComment=""</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("_locID_text=\"MaxOSVersion\" _locComment=\"\"")]
        [System.Xml.Serialization.XmlElementAttribute("MaxOSVersion", Namespace="http://schemas.microsoft.com/developer/vstemplate/2005")]
        public string MaxOSVersion { get; set; }
        
        /// <summary>
        /// <para>_locID_text="SpecialTemplateType" _locComment=""</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("_locID_text=\"SpecialTemplateType\" _locComment=\"\"")]
        [System.Xml.Serialization.XmlElementAttribute("SpecialTemplateType", Namespace="http://schemas.microsoft.com/developer/vstemplate/2005")]
        public TemplateDataSpecialTemplateType SpecialTemplateType { get; set; }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die SpecialTemplateType-Eigenschaft spezifiziert ist, oder legt diesen fest.</para>
        /// <para xml:lang="en">Gets or sets a value indicating whether the SpecialTemplateType property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SpecialTemplateTypeSpecified { get; set; }
        
        /// <summary>
        /// <para>_locID_text="CustomDataSignature" _locComment=""</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("_locID_text=\"CustomDataSignature\" _locComment=\"\"")]
        [System.Xml.Serialization.XmlElementAttribute("CustomDataSignature", Namespace="http://schemas.microsoft.com/developer/vstemplate/2005")]
        public string CustomDataSignature { get; set; }
        
        /// <summary>
        /// <para>_locID_text="AppIdFilter" _locComment=""</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("_locID_text=\"AppIdFilter\" _locComment=\"\"")]
        [System.Xml.Serialization.XmlElementAttribute("AppIdFilter", Namespace="http://schemas.microsoft.com/developer/vstemplate/2005")]
        public string AppIdFilter { get; set; }
        
        /// <summary>
        /// <para>_locID_text="LanguageTag" _locComment=""</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("_locID_text=\"LanguageTag\" _locComment=\"\"")]
        [System.Xml.Serialization.XmlElementAttribute("LanguageTag", Namespace="http://schemas.microsoft.com/developer/vstemplate/2005")]
        public string LanguageTag { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<string> _platformTag;
        
        /// <summary>
        /// <para>_locID_text="PlatformTag" _locComment=""</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("_locID_text=\"PlatformTag\" _locComment=\"\"")]
        [System.Xml.Serialization.XmlElementAttribute("PlatformTag", Namespace="http://schemas.microsoft.com/developer/vstemplate/2005")]
        public System.Collections.ObjectModel.Collection<string> PlatformTag
        {
            get
            {
                return this._platformTag;
            }
            private set
            {
                this._platformTag = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="TemplateData" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="TemplateData" /> class.</para>
        /// </summary>
        public TemplateData()
        {
            this._platformTag = new System.Collections.ObjectModel.Collection<string>();
            this._projectTypeTag = new System.Collections.ObjectModel.Collection<string>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<string> _projectTypeTag;
        
        /// <summary>
        /// <para>_locID_text="ProjectTypeTag" _locComment=""</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("_locID_text=\"ProjectTypeTag\" _locComment=\"\"")]
        [System.Xml.Serialization.XmlElementAttribute("ProjectTypeTag", Namespace="http://schemas.microsoft.com/developer/vstemplate/2005")]
        public System.Collections.ObjectModel.Collection<string> ProjectTypeTag
        {
            get
            {
                return this._projectTypeTag;
            }
            private set
            {
                this._projectTypeTag = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TemplateDataLocationField", Namespace="http://schemas.microsoft.com/developer/vstemplate/2005")]
    public enum TemplateDataLocationField
    {
        
        Enabled,
        
        Disabled,
        
        Hidden,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TemplateDataRequiredFrameworkVersion", Namespace="http://schemas.microsoft.com/developer/vstemplate/2005")]
    public enum TemplateDataRequiredFrameworkVersion
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("2.0")]
        Item2Period0,
        
        [System.Xml.Serialization.XmlEnumAttribute("3.0")]
        Item3Period0,
        
        [System.Xml.Serialization.XmlEnumAttribute("3.5")]
        Item3Period5,
        
        [System.Xml.Serialization.XmlEnumAttribute("4.0")]
        Item4Period0,
        
        [System.Xml.Serialization.XmlEnumAttribute("4.5")]
        Item4Period5,
        
        [System.Xml.Serialization.XmlEnumAttribute("4.5.1")]
        Item4Period5Period1,
        
        [System.Xml.Serialization.XmlEnumAttribute("4.5.2")]
        Item4Period5Period2,
        
        [System.Xml.Serialization.XmlEnumAttribute("4.6")]
        Item4Period6,
        
        [System.Xml.Serialization.XmlEnumAttribute("4.6.1")]
        Item4Period6Period1,
        
        [System.Xml.Serialization.XmlEnumAttribute("4.6.2")]
        Item4Period6Period2,
        
        [System.Xml.Serialization.XmlEnumAttribute("4.7")]
        Item4Period7,
        
        [System.Xml.Serialization.XmlEnumAttribute("4.7.1")]
        Item4Period7Period1,
        
        [System.Xml.Serialization.XmlEnumAttribute("4.7.2")]
        Item4Period7Period2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TemplateDataMaxFrameworkVersion", Namespace="http://schemas.microsoft.com/developer/vstemplate/2005")]
    public enum TemplateDataMaxFrameworkVersion
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("2.0")]
        Item2Period0,
        
        [System.Xml.Serialization.XmlEnumAttribute("3.0")]
        Item3Period0,
        
        [System.Xml.Serialization.XmlEnumAttribute("3.5")]
        Item3Period5,
        
        [System.Xml.Serialization.XmlEnumAttribute("4.0")]
        Item4Period0,
        
        [System.Xml.Serialization.XmlEnumAttribute("4.5")]
        Item4Period5,
        
        [System.Xml.Serialization.XmlEnumAttribute("4.5.1")]
        Item4Period5Period1,
        
        [System.Xml.Serialization.XmlEnumAttribute("4.5.2")]
        Item4Period5Period2,
        
        [System.Xml.Serialization.XmlEnumAttribute("4.6")]
        Item4Period6,
        
        [System.Xml.Serialization.XmlEnumAttribute("4.6.1")]
        Item4Period6Period1,
        
        [System.Xml.Serialization.XmlEnumAttribute("4.6.2")]
        Item4Period6Period2,
        
        [System.Xml.Serialization.XmlEnumAttribute("4.7")]
        Item4Period7,
        
        [System.Xml.Serialization.XmlEnumAttribute("4.7.1")]
        Item4Period7Period1,
        
        [System.Xml.Serialization.XmlEnumAttribute("4.7.2")]
        Item4Period7Period2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TemplateDataSpecialTemplateType", Namespace="http://schemas.microsoft.com/developer/vstemplate/2005")]
    public enum TemplateDataSpecialTemplateType
    {
        
        EmptyShared,
        
        EmptyNode,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("VSTemplateTemplateContent", Namespace="http://schemas.microsoft.com/developer/vstemplate/2005", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VSTemplateTemplateContent
    {
        
        /// <summary>
        /// <para>_locID_text="ProjectCollection" _locComment=""</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("_locID_text=\"ProjectCollection\" _locComment=\"\"")]
        [System.Xml.Serialization.XmlElementAttribute("ProjectCollection", Namespace="http://schemas.microsoft.com/developer/vstemplate/2005")]
        public VSTemplateTemplateContentProjectCollection ProjectCollection { get; set; }
        
        /// <summary>
        /// <para>_locID_text="TemplateContent.Project" _locComment=""</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("_locID_text=\"TemplateContent.Project\" _locComment=\"\"")]
        [System.Xml.Serialization.XmlElementAttribute("Project", Namespace="http://schemas.microsoft.com/developer/vstemplate/2005")]
        public VSTemplateTemplateContentProject Project { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<VSTemplateTemplateContentReferencesReference> _references;
        
        /// <summary>
        /// <para>_locID_text="TemplateContent.References" _locComment=""</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("_locID_text=\"TemplateContent.References\" _locComment=\"\"")]
        [System.Xml.Serialization.XmlArrayAttribute("References", Namespace="http://schemas.microsoft.com/developer/vstemplate/2005")]
        [System.Xml.Serialization.XmlArrayItemAttribute("Reference", Namespace="http://schemas.microsoft.com/developer/vstemplate/2005")]
        public System.Collections.ObjectModel.Collection<VSTemplateTemplateContentReferencesReference> References
        {
            get
            {
                return this._references;
            }
            private set
            {
                this._references = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die References-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the References collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReferencesSpecified
        {
            get
            {
                return (this.References.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="VSTemplateTemplateContent" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="VSTemplateTemplateContent" /> class.</para>
        /// </summary>
        public VSTemplateTemplateContent()
        {
            this._references = new System.Collections.ObjectModel.Collection<VSTemplateTemplateContentReferencesReference>();
            this._folder = new System.Collections.ObjectModel.Collection<Folder>();
            this._projectItem = new System.Collections.ObjectModel.Collection<VSTemplateTemplateContentProjectItem>();
            this._customParameters = new System.Collections.ObjectModel.Collection<VSTemplateTemplateContentCustomParametersCustomParameter>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Folder> _folder;
        
        [System.Xml.Serialization.XmlElementAttribute("Folder", Namespace="http://schemas.microsoft.com/developer/vstemplate/2005")]
        public System.Collections.ObjectModel.Collection<Folder> Folder
        {
            get
            {
                return this._folder;
            }
            private set
            {
                this._folder = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die Folder-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the Folder collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FolderSpecified
        {
            get
            {
                return (this.Folder.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<VSTemplateTemplateContentProjectItem> _projectItem;
        
        /// <summary>
        /// <para>_locID_text="ProjectItem" _locComment=""</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("_locID_text=\"ProjectItem\" _locComment=\"\"")]
        [System.Xml.Serialization.XmlElementAttribute("ProjectItem", Namespace="http://schemas.microsoft.com/developer/vstemplate/2005")]
        public System.Collections.ObjectModel.Collection<VSTemplateTemplateContentProjectItem> ProjectItem
        {
            get
            {
                return this._projectItem;
            }
            private set
            {
                this._projectItem = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die ProjectItem-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the ProjectItem collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ProjectItemSpecified
        {
            get
            {
                return (this.ProjectItem.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<VSTemplateTemplateContentCustomParametersCustomParameter> _customParameters;
        
        /// <summary>
        /// <para>_locID_text="TemplateContent.CustomParameters" _locComment=""</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("_locID_text=\"TemplateContent.CustomParameters\" _locComment=\"\"")]
        [System.Xml.Serialization.XmlArrayAttribute("CustomParameters", Namespace="http://schemas.microsoft.com/developer/vstemplate/2005")]
        [System.Xml.Serialization.XmlArrayItemAttribute("CustomParameter", Namespace="http://schemas.microsoft.com/developer/vstemplate/2005")]
        public System.Collections.ObjectModel.Collection<VSTemplateTemplateContentCustomParametersCustomParameter> CustomParameters
        {
            get
            {
                return this._customParameters;
            }
            private set
            {
                this._customParameters = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die CustomParameters-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the CustomParameters collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CustomParametersSpecified
        {
            get
            {
                return (this.CustomParameters.Count != 0);
            }
        }
        
        /// <summary>
        /// <para>_locID_text="TemplateContent.PreferedSolutionConfiguration" _locComment=""</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("_locID_text=\"TemplateContent.PreferedSolutionConfiguration\" _locComment=\"\"")]
        [System.Xml.Serialization.XmlAttributeAttribute("PreferedSolutionConfiguration", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PreferedSolutionConfiguration { get; set; }
        
        /// <summary>
        /// <para>_locID_text="TemplateContent.BuildOnLoad" _locComment=""</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("_locID_text=\"TemplateContent.BuildOnLoad\" _locComment=\"\"")]
        [System.Xml.Serialization.XmlAttributeAttribute("BuildOnLoad", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool BuildOnLoad { get; set; }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die BuildOnLoad-Eigenschaft spezifiziert ist, oder legt diesen fest.</para>
        /// <para xml:lang="en">Gets or sets a value indicating whether the BuildOnLoad property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BuildOnLoadSpecified { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("VSTemplateTemplateContentProjectCollection", Namespace="http://schemas.microsoft.com/developer/vstemplate/2005", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VSTemplateTemplateContentProjectCollection
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<ProjectTemplateLink> _projectTemplateLink;
        
        [System.Xml.Serialization.XmlElementAttribute("ProjectTemplateLink", Namespace="http://schemas.microsoft.com/developer/vstemplate/2005")]
        public System.Collections.ObjectModel.Collection<ProjectTemplateLink> ProjectTemplateLink
        {
            get
            {
                return this._projectTemplateLink;
            }
            private set
            {
                this._projectTemplateLink = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die ProjectTemplateLink-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the ProjectTemplateLink collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ProjectTemplateLinkSpecified
        {
            get
            {
                return (this.ProjectTemplateLink.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="VSTemplateTemplateContentProjectCollection" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="VSTemplateTemplateContentProjectCollection" /> class.</para>
        /// </summary>
        public VSTemplateTemplateContentProjectCollection()
        {
            this._projectTemplateLink = new System.Collections.ObjectModel.Collection<ProjectTemplateLink>();
            this._solutionFolder = new System.Collections.ObjectModel.Collection<SolutionFolder>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<SolutionFolder> _solutionFolder;
        
        [System.Xml.Serialization.XmlElementAttribute("SolutionFolder", Namespace="http://schemas.microsoft.com/developer/vstemplate/2005")]
        public System.Collections.ObjectModel.Collection<SolutionFolder> SolutionFolder
        {
            get
            {
                return this._solutionFolder;
            }
            private set
            {
                this._solutionFolder = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die SolutionFolder-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the SolutionFolder collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SolutionFolderSpecified
        {
            get
            {
                return (this.SolutionFolder.Count != 0);
            }
        }
    }
    
    /// <summary>
    /// <para>_locID_text="ProjectTemplateLink" _locComment=""</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("_locID_text=\"ProjectTemplateLink\" _locComment=\"\"")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ProjectTemplateLink", Namespace="http://schemas.microsoft.com/developer/vstemplate/2005")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("ProjectTemplateLink", Namespace="http://schemas.microsoft.com/developer/vstemplate/2005")]
    public partial class ProjectTemplateLink
    {
        
        /// <summary>
        /// <para xml:lang="de">Ruft den Text ab oder legt diesen fest.</para>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// </summary>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value { get; set; }
        
        /// <summary>
        /// <para>_locID_text="ProjectTemplateLink.ProjectName" _locComment=""</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("_locID_text=\"ProjectTemplateLink.ProjectName\" _locComment=\"\"")]
        [System.Xml.Serialization.XmlAttributeAttribute("ProjectName", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ProjectName { get; set; }
        
        /// <summary>
        /// <para>_locID_text="ProjectTemplateLink.CopyParameters" _locComment=""</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("_locID_text=\"ProjectTemplateLink.CopyParameters\" _locComment=\"\"")]
        [System.Xml.Serialization.XmlAttributeAttribute("CopyParameters", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool CopyParameters { get; set; }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die CopyParameters-Eigenschaft spezifiziert ist, oder legt diesen fest.</para>
        /// <para xml:lang="en">Gets or sets a value indicating whether the CopyParameters property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CopyParametersSpecified { get; set; }
    }
    
    /// <summary>
    /// <para>_locID_text="SolutionFolder" _locComment=""</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("_locID_text=\"SolutionFolder\" _locComment=\"\"")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("SolutionFolder", Namespace="http://schemas.microsoft.com/developer/vstemplate/2005", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("SolutionFolder", Namespace="http://schemas.microsoft.com/developer/vstemplate/2005")]
    public partial class SolutionFolder
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<ProjectTemplateLink> _projectTemplateLink;
        
        [System.Xml.Serialization.XmlElementAttribute("ProjectTemplateLink", Namespace="http://schemas.microsoft.com/developer/vstemplate/2005")]
        public System.Collections.ObjectModel.Collection<ProjectTemplateLink> ProjectTemplateLink
        {
            get
            {
                return this._projectTemplateLink;
            }
            private set
            {
                this._projectTemplateLink = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die ProjectTemplateLink-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the ProjectTemplateLink collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ProjectTemplateLinkSpecified
        {
            get
            {
                return (this.ProjectTemplateLink.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="SolutionFolder" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="SolutionFolder" /> class.</para>
        /// </summary>
        public SolutionFolder()
        {
            this._projectTemplateLink = new System.Collections.ObjectModel.Collection<ProjectTemplateLink>();
            this._solutionFolderProperty = new System.Collections.ObjectModel.Collection<SolutionFolder>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<SolutionFolder> _solutionFolderProperty;
        
        [System.Xml.Serialization.XmlElementAttribute("SolutionFolder", Namespace="http://schemas.microsoft.com/developer/vstemplate/2005")]
        public System.Collections.ObjectModel.Collection<SolutionFolder> SolutionFolderProperty
        {
            get
            {
                return this._solutionFolderProperty;
            }
            private set
            {
                this._solutionFolderProperty = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die SolutionFolderProperty-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the SolutionFolderProperty collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SolutionFolderPropertySpecified
        {
            get
            {
                return (this.SolutionFolderProperty.Count != 0);
            }
        }
        
        /// <summary>
        /// <para>_locID_text="SolutionFolder.Name" _locComment=""</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("_locID_text=\"SolutionFolder.Name\" _locComment=\"\"")]
        [System.Xml.Serialization.XmlAttributeAttribute("Name", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Name { get; set; }
        
        /// <summary>
        /// <para>_locID_text="SolutionFolder.CreateOnDisk" _locComment=""</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("_locID_text=\"SolutionFolder.CreateOnDisk\" _locComment=\"\"")]
        [System.Xml.Serialization.XmlAttributeAttribute("CreateOnDisk", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool CreateOnDisk { get; set; }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die CreateOnDisk-Eigenschaft spezifiziert ist, oder legt diesen fest.</para>
        /// <para xml:lang="en">Gets or sets a value indicating whether the CreateOnDisk property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CreateOnDiskSpecified { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("VSTemplateTemplateContentProject", Namespace="http://schemas.microsoft.com/developer/vstemplate/2005", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VSTemplateTemplateContentProject
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Folder> _folder;
        
        [System.Xml.Serialization.XmlElementAttribute("Folder", Namespace="http://schemas.microsoft.com/developer/vstemplate/2005")]
        public System.Collections.ObjectModel.Collection<Folder> Folder
        {
            get
            {
                return this._folder;
            }
            private set
            {
                this._folder = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die Folder-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the Folder collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FolderSpecified
        {
            get
            {
                return (this.Folder.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="VSTemplateTemplateContentProject" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="VSTemplateTemplateContentProject" /> class.</para>
        /// </summary>
        public VSTemplateTemplateContentProject()
        {
            this._folder = new System.Collections.ObjectModel.Collection<Folder>();
            this._projectItem = new System.Collections.ObjectModel.Collection<ProjectItem>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<ProjectItem> _projectItem;
        
        [System.Xml.Serialization.XmlElementAttribute("ProjectItem", Namespace="http://schemas.microsoft.com/developer/vstemplate/2005")]
        public System.Collections.ObjectModel.Collection<ProjectItem> ProjectItem
        {
            get
            {
                return this._projectItem;
            }
            private set
            {
                this._projectItem = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die ProjectItem-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the ProjectItem collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ProjectItemSpecified
        {
            get
            {
                return (this.ProjectItem.Count != 0);
            }
        }
        
        /// <summary>
        /// <para>_locID_text="TemplateContent.File" _locComment=""</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("_locID_text=\"TemplateContent.File\" _locComment=\"\"")]
        [System.Xml.Serialization.XmlAttributeAttribute("File", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string File { get; set; }
        
        /// <summary>
        /// <para>_locID_text="TemplateContent.TargetFileName" _locComment=""</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("_locID_text=\"TemplateContent.TargetFileName\" _locComment=\"\"")]
        [System.Xml.Serialization.XmlAttributeAttribute("TargetFileName", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TargetFileName { get; set; }
        
        /// <summary>
        /// <para>_locID_text="TemplateContent.ReplaceParameters" _locComment=""</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("_locID_text=\"TemplateContent.ReplaceParameters\" _locComment=\"\"")]
        [System.Xml.Serialization.XmlAttributeAttribute("ReplaceParameters", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool ReplaceParameters { get; set; }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die ReplaceParameters-Eigenschaft spezifiziert ist, oder legt diesen fest.</para>
        /// <para xml:lang="en">Gets or sets a value indicating whether the ReplaceParameters property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReplaceParametersSpecified { get; set; }
        
        /// <summary>
        /// <para>_locID_text="TemplateContent.IgnoreProjectParameter" _locComment=""</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("_locID_text=\"TemplateContent.IgnoreProjectParameter\" _locComment=\"\"")]
        [System.Xml.Serialization.XmlAttributeAttribute("IgnoreProjectParameter", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IgnoreProjectParameter { get; set; }
    }
    
    /// <summary>
    /// <para>_locID_text="Folder" _locComment=""</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("_locID_text=\"Folder\" _locComment=\"\"")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("Folder", Namespace="http://schemas.microsoft.com/developer/vstemplate/2005", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("Folder", Namespace="http://schemas.microsoft.com/developer/vstemplate/2005")]
    public partial class Folder
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<ProjectItem> _projectItem;
        
        [System.Xml.Serialization.XmlElementAttribute("ProjectItem", Namespace="http://schemas.microsoft.com/developer/vstemplate/2005")]
        public System.Collections.ObjectModel.Collection<ProjectItem> ProjectItem
        {
            get
            {
                return this._projectItem;
            }
            private set
            {
                this._projectItem = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die ProjectItem-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the ProjectItem collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ProjectItemSpecified
        {
            get
            {
                return (this.ProjectItem.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="Folder" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="Folder" /> class.</para>
        /// </summary>
        public Folder()
        {
            this._projectItem = new System.Collections.ObjectModel.Collection<ProjectItem>();
            this._folderProperty = new System.Collections.ObjectModel.Collection<Folder>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Folder> _folderProperty;
        
        [System.Xml.Serialization.XmlElementAttribute("Folder", Namespace="http://schemas.microsoft.com/developer/vstemplate/2005")]
        public System.Collections.ObjectModel.Collection<Folder> FolderProperty
        {
            get
            {
                return this._folderProperty;
            }
            private set
            {
                this._folderProperty = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die FolderProperty-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the FolderProperty collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FolderPropertySpecified
        {
            get
            {
                return (this.FolderProperty.Count != 0);
            }
        }
        
        /// <summary>
        /// <para>_locID_text="Folder.Name" _locComment=""</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("_locID_text=\"Folder.Name\" _locComment=\"\"")]
        [System.Xml.Serialization.XmlAttributeAttribute("Name", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Name { get; set; }
        
        /// <summary>
        /// <para>_locID_text="Folder.TargetFolderName" _locComment=""</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("_locID_text=\"Folder.TargetFolderName\" _locComment=\"\"")]
        [System.Xml.Serialization.XmlAttributeAttribute("TargetFolderName", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TargetFolderName { get; set; }
    }
    
    /// <summary>
    /// <para>_locID_text="ProjectItem" _locComment=""</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("_locID_text=\"ProjectItem\" _locComment=\"\"")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ProjectItem", Namespace="http://schemas.microsoft.com/developer/vstemplate/2005")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("ProjectItem", Namespace="http://schemas.microsoft.com/developer/vstemplate/2005")]
    public partial class ProjectItem
    {
        
        /// <summary>
        /// <para xml:lang="de">Ruft den Text ab oder legt diesen fest.</para>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// </summary>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value { get; set; }
        
        /// <summary>
        /// <para>_locID_text="ProjectItem.SubType" _locComment=""</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("_locID_text=\"ProjectItem.SubType\" _locComment=\"\"")]
        [System.Xml.Serialization.XmlAttributeAttribute("SubType", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SubType { get; set; }
        
        /// <summary>
        /// <para>_locID_text="ProjectItem.CustomTool" _locComment=""</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("_locID_text=\"ProjectItem.CustomTool\" _locComment=\"\"")]
        [System.Xml.Serialization.XmlAttributeAttribute("CustomTool", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CustomTool { get; set; }
        
        /// <summary>
        /// <para>_locID_text="ProjectItem.ItemType" _locComment=""</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("_locID_text=\"ProjectItem.ItemType\" _locComment=\"\"")]
        [System.Xml.Serialization.XmlAttributeAttribute("ItemType", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ItemType { get; set; }
        
        /// <summary>
        /// <para>_locID_text="ProjectItem.TargetFileName" _locComment=""</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("_locID_text=\"ProjectItem.TargetFileName\" _locComment=\"\"")]
        [System.Xml.Serialization.XmlAttributeAttribute("TargetFileName", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TargetFileName { get; set; }
        
        /// <summary>
        /// <para>_locID_text="ProjectItem.ReplaceParameters2" _locComment=""</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("_locID_text=\"ProjectItem.ReplaceParameters2\" _locComment=\"\"")]
        [System.Xml.Serialization.XmlAttributeAttribute("ReplaceParameters", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool ReplaceParameters { get; set; }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die ReplaceParameters-Eigenschaft spezifiziert ist, oder legt diesen fest.</para>
        /// <para xml:lang="en">Gets or sets a value indicating whether the ReplaceParameters property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReplaceParametersSpecified { get; set; }
        
        /// <summary>
        /// <para>_locID_text="OpenInEditor" _locComment=""</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("_locID_text=\"OpenInEditor\" _locComment=\"\"")]
        [System.Xml.Serialization.XmlAttributeAttribute("OpenInEditor", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OpenInEditor { get; set; }
        
        /// <summary>
        /// <para>_locID_text="OpenOrder" _locComment=""</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("_locID_text=\"OpenOrder\" _locComment=\"\"")]
        [System.Xml.Serialization.XmlAttributeAttribute("OpenOrder", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int OpenOrder { get; set; }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die OpenOrder-Eigenschaft spezifiziert ist, oder legt diesen fest.</para>
        /// <para xml:lang="en">Gets or sets a value indicating whether the OpenOrder property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OpenOrderSpecified { get; set; }
        
        /// <summary>
        /// <para>_locID_text="OpenInWebBrowser" _locComment=""</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("_locID_text=\"OpenInWebBrowser\" _locComment=\"\"")]
        [System.Xml.Serialization.XmlAttributeAttribute("OpenInWebBrowser", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool OpenInWebBrowser { get; set; }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die OpenInWebBrowser-Eigenschaft spezifiziert ist, oder legt diesen fest.</para>
        /// <para xml:lang="en">Gets or sets a value indicating whether the OpenInWebBrowser property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OpenInWebBrowserSpecified { get; set; }
        
        /// <summary>
        /// <para>_locID_text="OpenInHelpBrowser" _locComment=""</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("_locID_text=\"OpenInHelpBrowser\" _locComment=\"\"")]
        [System.Xml.Serialization.XmlAttributeAttribute("OpenInHelpBrowser", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool OpenInHelpBrowser { get; set; }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die OpenInHelpBrowser-Eigenschaft spezifiziert ist, oder legt diesen fest.</para>
        /// <para xml:lang="en">Gets or sets a value indicating whether the OpenInHelpBrowser property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OpenInHelpBrowserSpecified { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("VSTemplateTemplateContentReferences", Namespace="http://schemas.microsoft.com/developer/vstemplate/2005", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VSTemplateTemplateContentReferences
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<VSTemplateTemplateContentReferencesReference> _reference;
        
        /// <summary>
        /// <para>_locID_text="TemplateContent.Reference" _locComment=""</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("_locID_text=\"TemplateContent.Reference\" _locComment=\"\"")]
        [System.Xml.Serialization.XmlElementAttribute("Reference", Namespace="http://schemas.microsoft.com/developer/vstemplate/2005")]
        public System.Collections.ObjectModel.Collection<VSTemplateTemplateContentReferencesReference> Reference
        {
            get
            {
                return this._reference;
            }
            private set
            {
                this._reference = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die Reference-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the Reference collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReferenceSpecified
        {
            get
            {
                return (this.Reference.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="VSTemplateTemplateContentReferences" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="VSTemplateTemplateContentReferences" /> class.</para>
        /// </summary>
        public VSTemplateTemplateContentReferences()
        {
            this._reference = new System.Collections.ObjectModel.Collection<VSTemplateTemplateContentReferencesReference>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("VSTemplateTemplateContentReferencesReference", Namespace="http://schemas.microsoft.com/developer/vstemplate/2005", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VSTemplateTemplateContentReferencesReference
    {
        
        /// <summary>
        /// <para>_locID_text="TemplateContent.Assembly" _locComment=""</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("_locID_text=\"TemplateContent.Assembly\" _locComment=\"\"")]
        [System.Xml.Serialization.XmlElementAttribute("Assembly", Namespace="http://schemas.microsoft.com/developer/vstemplate/2005")]
        public string Assembly { get; set; }
        
        /// <summary>
        /// <para>_locID_text="TemplateContent.SDKReference" _locComment=""</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("_locID_text=\"TemplateContent.SDKReference\" _locComment=\"\"")]
        [System.Xml.Serialization.XmlElementAttribute("SDKReference", Namespace="http://schemas.microsoft.com/developer/vstemplate/2005")]
        public string SDKReference { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("VSTemplateTemplateContentProjectItem", Namespace="http://schemas.microsoft.com/developer/vstemplate/2005")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VSTemplateTemplateContentProjectItem
    {
        
        /// <summary>
        /// <para xml:lang="de">Ruft den Text ab oder legt diesen fest.</para>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// </summary>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value { get; set; }
        
        /// <summary>
        /// <para>_locID_text="ProjectItem.SubType" _locComment=""</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("_locID_text=\"ProjectItem.SubType\" _locComment=\"\"")]
        [System.Xml.Serialization.XmlAttributeAttribute("SubType", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SubType { get; set; }
        
        /// <summary>
        /// <para>_locID_text="ProjectItem.CustomTool" _locComment=""</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("_locID_text=\"ProjectItem.CustomTool\" _locComment=\"\"")]
        [System.Xml.Serialization.XmlAttributeAttribute("CustomTool", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CustomTool { get; set; }
        
        /// <summary>
        /// <para>_locID_text="ProjectItem.ItemType" _locComment=""</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("_locID_text=\"ProjectItem.ItemType\" _locComment=\"\"")]
        [System.Xml.Serialization.XmlAttributeAttribute("ItemType", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ItemType { get; set; }
        
        /// <summary>
        /// <para>_locID_text="ProjectItem.ReplaceParameters" _locComment=""</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("_locID_text=\"ProjectItem.ReplaceParameters\" _locComment=\"\"")]
        [System.Xml.Serialization.XmlAttributeAttribute("ReplaceParameters", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool ReplaceParameters { get; set; }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die ReplaceParameters-Eigenschaft spezifiziert ist, oder legt diesen fest.</para>
        /// <para xml:lang="en">Gets or sets a value indicating whether the ReplaceParameters property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReplaceParametersSpecified { get; set; }
        
        /// <summary>
        /// <para>_locID_text="ProjectItem.TargetFileName" _locComment=""</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("_locID_text=\"ProjectItem.TargetFileName\" _locComment=\"\"")]
        [System.Xml.Serialization.XmlAttributeAttribute("TargetFileName", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TargetFileName { get; set; }
        
        /// <summary>
        /// <para>_locID_text="DependentUpon" _locComment=""</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("_locID_text=\"DependentUpon\" _locComment=\"\"")]
        [System.Xml.Serialization.XmlAttributeAttribute("DependentUpon", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DependentUpon { get; set; }
        
        /// <summary>
        /// <para>_locID_text="OpenInEditor" _locComment=""</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("_locID_text=\"OpenInEditor\" _locComment=\"\"")]
        [System.Xml.Serialization.XmlAttributeAttribute("OpenInEditor", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OpenInEditor { get; set; }
        
        /// <summary>
        /// <para>_locID_text="OpenOrder" _locComment=""</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("_locID_text=\"OpenOrder\" _locComment=\"\"")]
        [System.Xml.Serialization.XmlAttributeAttribute("OpenOrder", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int OpenOrder { get; set; }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die OpenOrder-Eigenschaft spezifiziert ist, oder legt diesen fest.</para>
        /// <para xml:lang="en">Gets or sets a value indicating whether the OpenOrder property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OpenOrderSpecified { get; set; }
        
        /// <summary>
        /// <para>_locID_text="OpenInWebBrowser" _locComment=""</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("_locID_text=\"OpenInWebBrowser\" _locComment=\"\"")]
        [System.Xml.Serialization.XmlAttributeAttribute("OpenInWebBrowser", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool OpenInWebBrowser { get; set; }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die OpenInWebBrowser-Eigenschaft spezifiziert ist, oder legt diesen fest.</para>
        /// <para xml:lang="en">Gets or sets a value indicating whether the OpenInWebBrowser property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OpenInWebBrowserSpecified { get; set; }
        
        /// <summary>
        /// <para>_locID_text="OpenInHelpBrowser" _locComment=""</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("_locID_text=\"OpenInHelpBrowser\" _locComment=\"\"")]
        [System.Xml.Serialization.XmlAttributeAttribute("OpenInHelpBrowser", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool OpenInHelpBrowser { get; set; }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die OpenInHelpBrowser-Eigenschaft spezifiziert ist, oder legt diesen fest.</para>
        /// <para xml:lang="en">Gets or sets a value indicating whether the OpenInHelpBrowser property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OpenInHelpBrowserSpecified { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("VSTemplateTemplateContentCustomParameters", Namespace="http://schemas.microsoft.com/developer/vstemplate/2005", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VSTemplateTemplateContentCustomParameters
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<VSTemplateTemplateContentCustomParametersCustomParameter> _customParameter;
        
        /// <summary>
        /// <para>_locID_text="TemplateContent.CustomParameter" _locComment=""</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("_locID_text=\"TemplateContent.CustomParameter\" _locComment=\"\"")]
        [System.Xml.Serialization.XmlElementAttribute("CustomParameter", Namespace="http://schemas.microsoft.com/developer/vstemplate/2005")]
        public System.Collections.ObjectModel.Collection<VSTemplateTemplateContentCustomParametersCustomParameter> CustomParameter
        {
            get
            {
                return this._customParameter;
            }
            private set
            {
                this._customParameter = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="VSTemplateTemplateContentCustomParameters" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="VSTemplateTemplateContentCustomParameters" /> class.</para>
        /// </summary>
        public VSTemplateTemplateContentCustomParameters()
        {
            this._customParameter = new System.Collections.ObjectModel.Collection<VSTemplateTemplateContentCustomParametersCustomParameter>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("VSTemplateTemplateContentCustomParametersCustomParameter", Namespace="http://schemas.microsoft.com/developer/vstemplate/2005", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VSTemplateTemplateContentCustomParametersCustomParameter
    {
        
        [System.Xml.Serialization.XmlAttributeAttribute("Name", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Name { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("Value", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Value { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("VSTemplateWizardExtension", Namespace="http://schemas.microsoft.com/developer/vstemplate/2005", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VSTemplateWizardExtension
    {
        
        [System.Xml.Serialization.XmlElementAttribute("Assembly", Namespace="http://schemas.microsoft.com/developer/vstemplate/2005")]
        public string Assembly { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("FullClassName", Namespace="http://schemas.microsoft.com/developer/vstemplate/2005")]
        public string FullClassName { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("VSTemplateWizardData", Namespace="http://schemas.microsoft.com/developer/vstemplate/2005", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VSTemplateWizardData
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<System.Xml.XmlElement> _any;
        
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Collections.ObjectModel.Collection<System.Xml.XmlElement> Any
        {
            get
            {
                return this._any;
            }
            private set
            {
                this._any = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die Any-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the Any collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AnySpecified
        {
            get
            {
                return (this.Any.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="VSTemplateWizardData" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="VSTemplateWizardData" /> class.</para>
        /// </summary>
        public VSTemplateWizardData()
        {
            this._any = new System.Collections.ObjectModel.Collection<System.Xml.XmlElement>();
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute("Name", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Name { get; set; }
    }
}
