name: ci

on:
  push:
    branches: [ master ]
    paths:
    - '.github/workflows/ci.yml'
    - 'Directory.Build.props'
    - 'src/**'
  pull_request:
    branches: [ master ]

env:
  DOTNET_NOLOGO: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        source-url: https://nuget.pkg.github.com/jjagg/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Pack NuGet
      working-directory: ./src
      run: dotnet pack -c Release -o out

    - name: Push NuGet package to GPR
      run: dotnet nuget push src/out/*.nupkg --skip-duplicate
